amcl:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "dummy_link"
    scan_topic: scan
    map_topic: map
    set_initial_pose: true
    always_reset_initial_pose: true
    first_map_only: false
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    